{% set name = "fakechroot" %}
{% set version = "2.20.1" %}
{% set sha256 = "7f9d60d0d48611969e195fadf84d05f6c74f71bbf8f41950ad8f5bf061773e18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dex4er/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool >=2.0
    - automake >=1.10
    - make

test:
  commands:
    - test -f "${PREFIX}/bin/fakechroot"

about:
  home: http://github.com/dex4er/fakechroot
  license: LGPL-2.1-only
  license_family: LGPL
  license_file: LICENSE
  summary: fakechroot runs a command in an environment without requiring root privileges

  description: |
    fakechroot runs a command in an environment were is additional possibility
    to use chroot(8) command without root privileges. This is useful for
    allowing users to create own chrooted environment with possibility to
    install another packages without need for root privileges.
  dev_url: http://github.com/dex4er/fakechroot

extra:
  recipe-maintainers:
    - scopatz
